# Generated by Django 4.0.1 on 2022-02-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на профиль'),
        ),
    ]
