# Generated by Django 3.2.9 on 2022-01-20 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220116_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описанние'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(default='Unknown', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок'),
        ),
    ]
