# Generated by Django 3.2.9 on 2022-01-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220120_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начало')),
                ('date_end', models.DateField(verbose_name='Дата конца')),
                ('name', models.CharField(default='Unknown', max_length=200, verbose_name='Название')),
                ('descriptions', models.TextField(default='Missing', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project'),
            preserve_default=False,
        ),
    ]
