# Generated by Django 3.2.9 on 2022-01-31 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220131_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.TextField(default='Missing', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Unknown', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название'),
        ),
    ]
