# Generated by Django 3.2.9 on 2022-02-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_projectuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
